-- Migration 002: Domain State Enums
CREATE TYPE risk_tier_enum AS ENUM ('TIER_1_MILD', 'TIER_2_MODERATE', 'TIER_3_HIGH', 'TIER_4_CRITICAL');
CREATE TYPE channel_enum AS ENUM ('NHAA_14566', 'IVRS_OUTBOUND', 'WEB_PORTAL', 'MOBILE_APP', 'WHATSAPP_BOT', 'FIELD_COUNSELOR');
CREATE TYPE milestone_type_enum AS ENUM ('FIR_REGISTERED', 'CHARGESHEET_FILED', 'ACCUSED_ARRESTED', 'BAIL_HEARING', 'TRIAL_HEARING', 'WITNESS_DEPOSITION', 'JUDGMENT_DELIVERED', 'COMPENSATION_RELEASE');
CREATE TYPE alert_status_enum AS ENUM ('TRIGGERED', 'IN_TRIAGE', 'HUMAN_VERIFIED', 'ACTION_DISPATCHED', 'RESOLVED_CLOSED', 'FALSE_POSITIVE');
CREATE TYPE intervention_type_enum AS ENUM ('CRISIS_TELE_COUNSELING', 'PSYCHIATRIC_REFERRAL', 'WITNESS_POLICE_PROTECTION', 'EMERGENCY_RELOCATION', 'LEGAL_AID_DLSA', 'COMPENSATION_FASTTRACK');
CREATE TYPE user_role_enum AS ENUM ('SUPER_ADMIN', 'NATIONAL_MONITOR', 'STATE_NODAL_OFFICER', 'DISTRICT_MAGISTRATE', 'SUPERINTENDENT_OF_POLICE', 'DLSA_SECRETARY', 'DISTRICT_WELFARE_OFFICER', 'CERTIFIED_COUNSELOR');
